db-uri = "postgres://postgres:dev%40indiebase.com@postgres:5432/indiebase-dev?sslmode=disable"
db-schemas = "public,proj_01kxbfehgsbqjvgkk0qe2epz39,proj_01kxbfg0g5zarx41ypbbcn89f1,proj_01kxbfhgzf8ec18c7b2tsvd2nr,proj_01kxbfqfcpc2evdg2v0kvw1eyg,proj_01kxbfwkve863d1wd1n135jykp,proj_01kxe18ncpny7cff5sda8f6542"
db-anon-role = "anon"
openapi-server-proxy-uri = "http://localhost:13000"
